#pragma once
#include <windows.h>
#include <stdlib.h>
#include <string.h>
#include <tchar.h>
#include <Wincrypt.h>
#include <stdio.h>
#include <string>
#include <fstream>
#include <filesystem>
#include <set>
#include <thread>
#include "../imgui/imgui.h"
